name: Buildx (push to master)

on:
  push:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v2
        with:
          buildx-version: latest
          skip-cache: false
          qemu-version: latest

      - name: Build images
        run: |
          docker buildx build \
            --platform linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            -t wildwildangel/mysql-honeypotd:latest \
            .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u wildwildangel --password-stdin

      - name: Push images
        run: |
          docker buildx build \
            --platform linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            -t wildwildangel/mysql-honeypotd:latest \
            . \
            --push
